### ISSUE TITLE
Yellow Tech Artillery Shell

### ISSUE THREAD

**Issue by abaines** [abaines/VN-Artillery#1]
https://mods.factorio.com/mod/lightArtillery/discussion/5ea5bcddf44b6b000c178a6a

Need more resource efficient shell somewhere around blue tech (plus probably Military) (pre-yellow or purple).

**Comment by abaines** [comment]
>Thuro:  I like the idea of perhaps a shell that isn't 100% accurate. Does the game allow for decreasing accuracy/randomizing shots via mod? I would be interested to see a variant of this mod that shoots much faster but with less range and accuracy. Sort of an artillery carpet bomb. Or perhaps one shot that has a spread like a barrage?

https://mods.factorio.com/mod/lightArtillery/discussion/5d9ca4d8d76ca6000d651cd1
@ducttapecoder-vt

**Comment by abaines** [comment]
@ducttapecoder-vt 
I think this mostly [just needs English](https://github.com/abaines/VN-Artillery/blob/cluster-ammo/locale/en/locale.cfg) and ready for first balance play test (or release).

### Recipe Ingredient Comparison
https://kirkmcdonald.github.io/calc.html#items=artillery-shell:r:1

https://kirkmcdonald.github.io/calc.html#items=coal:r:6,steel-plate:r:6,empty-barrel:r:6,water:r:300,advanced-circuit:r:1,explosives:r:1,lubricant:r:5

**Comment by abaines** [comment]
https://github.com/abaines/VN-Artillery/compare/cluster-ammo

**Comment by ducttapecoder-vt** [comment]
https://en.wikipedia.org/wiki/BLU-3_Pineapple !!

**Comment by abaines** [comment]
https://github.com/abaines/VN-Artillery/releases/tag/0.4.13

**Comment by abaines** [comment]
![image](https://user-images.githubusercontent.com/4323841/87218668-c1720180-c322-11ea-8ff5-8a1c24cf892e.png)
This ended up being Yellow science, but I do have plans for a Military-3 (Blue Science) ammo.
